language: groovy
jdk:
  - openjdk7

script:
  - ./grailsw refresh-dependencies --non-interactive
  - ./grailsw test-app -coverage -xml

notifications:
  email:
    recipients:
      - lopez.ivan@gmail.com

    on_success: change
    on_failure: change

after_success:
  - ./grailsw coveralls